### ISSUE TITLE
Manage application networks

### ISSUE THREAD

**Issue by noof-eu** [OsgiliathEnterprise/platform#66]
# Category:

[ What business added value do you want to add? ]
    In order to enhance network security,
    As an architect,
    I want to have a network segregation between applications holding security rules. It will avoid unwanted access or malware data exfiltration.
 
# Target platform:

Will it be hosted on Orchestrator

# Integration:

[ Should it be integrated with other solution? ]
  

# Filled after ticket closed

## Category label

[What's the github ticket query to have all informations on tickets]

## Current solutions

[ Currently implemented or most voted one, will be filled once the vote is ended]

**Comment by Tcharl** [comment]
Hi @noof-eu ,

I have some little remarks concerning the format (not the content ;-)).

You filled a 'category' ticket, which purpose is to introduce new business solution to the platform.
Thus, as modifying the network isn't a new addition (it's a matter of design), the enhancement/feature request should have been more appropriate.

Finally, the 'Target Platform' section means the target platform where the feature shall be installed.

* Host meaning the host configuring the VMs, orchestrators or containers
* Containerization meaning Docker/LXC
* Orchestrator meaning Kubernetes/Cloud Foundry
* VM meaning a VM.

In this case, Network shall apply to everything listed below I think, not only Kube :-)

**Comment by Tcharl** [comment]
Good news: freeipa and qemu let you define VNets :-).

Want to give a try?

**Comment by Tcharl** [comment]
Also, istio system configuration is on the way
